import { NextRequest, NextResponse } from 'next/server'
import { getPrisma } from '@/lib/auth/prisma'
import { requireAdmin } from '@/lib/admin-auth'

const STORE_ID = 'store-fresh-mart-001'

/**
 * POST /api/admin/finance/email-report
 *
 * Triggers an email containing the finance report to the store owner.
 * Body (optional):
 *   { startDate?: string, endDate?: string }
 *
 * SMTP configuration:
 *   Reads SMTP_URL, SMTP_FROM, SMTP_USER, SMTP_PASS from env. If not
 *   configured, falls back to creating an in-app notification record
 *   so the owner still receives the report content (just not via email).
 *
 * In production, set the SMTP_* env vars in Vercel to enable real email.
 */
export async function POST(request: NextRequest) {
  const { error, user } = await requireAdmin({ feature: 'finance' })
  if (error) return error

  let startDate: string | undefined
  let endDate: string | undefined
  try {
    const body = await request.json()
    startDate = body.startDate
    endDate = body.endDate
  } catch {
    // Body may be empty — use defaults
  }

  try {
    const prisma = await getPrisma()

    // Fetch the same data as the report endpoint
    const end = endDate ? new Date(endDate + 'T23:59:59') : new Date()
    const start = startDate
      ? new Date(startDate + 'T00:00:00')
      : new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)

    const [orders, expenses, store, owner] = await Promise.all([
      prisma.order.findMany({
        where: {
          storeId: STORE_ID,
          createdAt: { gte: start, lte: end },
          status: { not: 'cancelled' },
        },
        select: { total: true, vatAmount: true, deliveryFee: true, paymentStatus: true },
      }),
      prisma.expense.findMany({
        where: { storeId: STORE_ID, date: { gte: start, lte: end } },
        select: { amount: true, category: true },
      }),
      prisma.store.findUnique({ where: { id: STORE_ID } }),
      prisma.user.findFirst({ where: { role: 'OWNER' } }),
    ])

    const totalRevenue = orders.reduce((s, o) => s + o.total, 0)
    const totalExpenses = expenses.reduce((s, e) => s + e.amount, 0)
    const profit = totalRevenue - totalExpenses

    const storeName = store?.name || 'Fresh Mart'
    const ownerEmail = owner?.email || store?.email

    if (!ownerEmail) {
      return NextResponse.json(
        { error: 'No owner email configured. Set the owner\'s email in Settings.' },
        { status: 400 }
      )
    }

    const periodLabel = `${start.toLocaleDateString('en-GB')} – ${end.toLocaleDateString('en-GB')}`

    const subject = `${storeName} Finance Report — ${periodLabel}`
    const textBody = [
      `${storeName} — Finance Report`,
      `Period: ${periodLabel}`,
      ``,
      `SUMMARY`,
      `  Revenue:    £${totalRevenue.toFixed(2)}`,
      `  Expenses:   £${totalExpenses.toFixed(2)}`,
      `  Profit:     £${profit.toFixed(2)}`,
      `  Orders:     ${orders.length}`,
      `  Expenses logged: ${expenses.length}`,
      ``,
      `Expense breakdown:`,
      ...Object.entries(
        expenses.reduce<Record<string, number>>((acc, e) => {
          acc[e.category] = (acc[e.category] || 0) + e.amount
          return acc
        }, {})
      ).map(([cat, amt]) => `  ${cat}: £${amt.toFixed(2)}`),
      ``,
      `Generated by Fresh Mart admin dashboard.`,
    ].join('\n')

    // Check if SMTP env vars are present
    const smtpUrl = process.env.SMTP_URL
    const smtpFrom = process.env.SMTP_FROM || 'no-reply@freshmart.local'
    const smtpUser = process.env.SMTP_USER
    const smtpPass = process.env.SMTP_PASS

    let emailSent = false
    let emailError: string | null = null

    if (smtpUrl && smtpUser && smtpPass) {
      try {
        // Dynamic import so the dependency isn't loaded if SMTP isn't configured
        const nodemailer = await import('nodemailer')
        const transporter = nodemailer.createTransport(smtpUrl)
        await transporter.sendMail({
          from: smtpFrom,
          to: ownerEmail,
          subject,
          text: textBody,
        })
        emailSent = true
      } catch (err: any) {
        console.error('[Finance Email] SMTP send failed:', err)
        emailError = err.message || 'SMTP error'
      }
    }

    // Always create an in-app notification record for the owner, regardless
    // of whether SMTP succeeded. This guarantees the report is delivered
    // somewhere the owner will see it.
    await prisma.notification.create({
      data: {
        userId: owner?.id || user.id,
        type: 'finance_report',
        title: subject,
        message: `Revenue £${totalRevenue.toFixed(2)} · Expenses £${totalExpenses.toFixed(2)} · Profit £${profit.toFixed(2)} (${orders.length} orders, ${expenses.length} expenses). ${emailSent ? 'Emailed to ' + ownerEmail : 'Email not sent — SMTP not configured. View full report in the admin Finance page.'}`,
        isRead: false,
      },
    })

    return NextResponse.json({
      success: true,
      emailSent,
      emailError,
      recipient: ownerEmail,
      summary: {
        totalRevenue,
        totalExpenses,
        profit,
        orderCount: orders.length,
        expenseCount: expenses.length,
      },
      message: emailSent
        ? `Report emailed to ${ownerEmail}`
        : `SMTP not configured (set SMTP_URL, SMTP_USER, SMTP_PASS, SMTP_FROM env vars). Report saved as in-app notification for the owner.`,
    })
  } catch (err) {
    console.error('[Finance Email POST]', err)
    return NextResponse.json({ error: 'Failed to send finance report email' }, { status: 500 })
  }
}
